# Generated by Django 4.0.5 on 2022-08-31 19:53

from django.db import migrations, models
import django.utils.timezone
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cost',
            field=models.IntegerField(help_text='Price of expense in smallest denomination. e.g. (£10 = 1000)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date that the expense was conducted.'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=expenses.models.LowercaseCharField(max_length=30),
        ),
    ]
